name: Android

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup codecov
        uses: codecov/codecov-action@v2
      
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build debug
        run: bash ./gradlew buildDebug
      
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - name: Generate code coverage reports
        run: bash ./gradlew createDebugCoverageReport

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov
